# Generated by Django 3.1.3 on 2020-11-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
