# Generated by Django 3.1.3 on 2020-11-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20201116_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_started', models.DateTimeField(auto_now=True)),
                ('date_end', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Started'), (1, 'Generated'), (10, 'Error')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='generated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generated_images', to='scrapper.resourcegeneration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='generated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generated_texts', to='scrapper.resourcegeneration'),
            preserve_default=False,
        ),
    ]
