# Generated by Django 3.1.3 on 2020-11-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_auto_20201116_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generated_images', to='scrapper.resourcegeneration'),
        ),
        migrations.AlterField(
            model_name='text',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generated_texts', to='scrapper.resourcegeneration'),
        ),
    ]
