# Generated by Django 3.1.3 on 2020-11-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_auto_20201116_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcegeneration',
            name='url',
            field=models.CharField(default='google.com', max_length=1000),
            preserve_default=False,
        ),
    ]
