# Generated by Django 3.1.3 on 2020-11-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_resourcegeneration_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegeneration',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
